# ================================
# Instance Configuration: {{INSTANCE_NAME}}
# Generated by instance-manager.sh
# ================================

# Instance identifier (used as Docker Compose project name)
COMPOSE_PROJECT_NAME={{INSTANCE_NAME}}

# Database
MONGODB_DB_NAME={{INSTANCE_NAME}}_db

# External ports (unique per instance to avoid conflicts)
API_PORT={{API_PORT}}
MONGODB_PORT={{MONGODB_PORT}}
REDIS_PORT={{REDIS_PORT}}
NGINX_HTTP_PORT={{NGINX_HTTP_PORT}}
NGINX_HTTPS_PORT={{NGINX_HTTPS_PORT}}
ADMINER_PORT={{ADMINER_PORT}}
REGISTRY_PORT={{REGISTRY_PORT}}
USER_PORTAL_PORT={{USER_PORTAL_PORT}}
USER_PORTAL_PROD_PORT={{USER_PORTAL_PROD_PORT}}
IOT_SIM_PORT={{IOT_SIM_PORT}}

# Nginx config path (points to instance-specific config)
NGINX_CONF={{NGINX_CONF}}

# Authentication
ADMIN_EMAIL=admin@a64platform.com
ADMIN_PASSWORD=SuperAdmin123!

# Redis
REDIS_PASSWORD=redispassword

# MongoDB
MONGO_APP_USER=a64core_app
MONGO_APP_PASSWORD=changeme_in_production
MONGO_ROOT_USERNAME=admin
MONGO_ROOT_PASSWORD=mongoadmin123

# Security (REQUIRED for production mode)
SECRET_KEY={{INSTANCE_NAME}}-secret-key-change-me-in-production

# API Keys (fill in as needed)
ANTHROPIC_API_KEY=
WEATHERBIT_API_KEY=
ELEVENLABS_API_KEY=

# Workers
UVICORN_WORKERS=4
