#!/usr/bin/env python3
"""
Initialize MongoDB collections and indexes for Operations Task Manager

Creates collections and indexes for:
- farm_tasks: Task management for farmers
- block_alerts: Issue reporting system
- farmer_assignments: Already exists, add additional indexes if needed

Run this script once to set up the database schema.
"""

import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
import os


async def init_operations_collections():
    """Initialize operations collections with indexes"""

    # MongoDB connection
    mongo_uri = os.getenv("MONGODB_URI", "mongodb://localhost:27017")
    database_name = os.getenv("DATABASE_NAME", "a64core_db")

    print(f"Connecting to MongoDB: {mongo_uri}")
    client = AsyncIOMotorClient(mongo_uri)
    db = client[database_name]

    print(f"Database: {database_name}")
    print("=" * 60)

    # ============================================================
    # 1. FARM_TASKS Collection
    # ============================================================
    print("\n[1/2] Creating farm_tasks collection and indexes...")

    # Create collection (if doesn't exist)
    if "farm_tasks" not in await db.list_collection_names():
        await db.create_collection("farm_tasks")
        print("[OK] Created farm_tasks collection")
    else:
        print("[INFO] farm_tasks collection already exists")

    # Create indexes for farm_tasks
    tasks_collection = db.farm_tasks

    # Index 1: Query tasks by farm and status
    await tasks_collection.create_index(
        [("farmId", 1), ("status", 1), ("scheduledDate", 1)],
        name="idx_farm_status_scheduled"
    )
    print("[OK] Created index: farmId + status + scheduledDate")

    # Index 2: Query tasks by block
    await tasks_collection.create_index(
        [("blockId", 1), ("status", 1)],
        name="idx_block_status"
    )
    print("[OK] Created index: blockId + status")

    # Index 3: Query tasks by user assignment (for custom tasks)
    await tasks_collection.create_index(
        [("assignedTo", 1), ("status", 1), ("dueDate", 1)],
        name="idx_assigned_status_due",
        sparse=True  # Only index documents where assignedTo exists
    )
    print("[OK] Created index: assignedTo + status + dueDate (sparse)")

    # Index 4: Query pending tasks by due date (for notifications)
    await tasks_collection.create_index(
        [("status", 1), ("dueDate", 1)],
        name="idx_status_duedate"
    )
    print("[OK] Created index: status + dueDate")

    # Index 5: Unique task ID
    await tasks_collection.create_index(
        [("taskId", 1)],
        name="idx_taskid_unique",
        unique=True
    )
    print("[OK] Created unique index: taskId")

    # Index 6: Query auto-generated tasks by cycle (for rescheduling)
    await tasks_collection.create_index(
        [("generatedFromCycleId", 1), ("isAutoGenerated", 1)],
        name="idx_cycle_autogen",
        sparse=True
    )
    print("[OK] Created index: generatedFromCycleId + isAutoGenerated (sparse)")

    # Index 7: Query daily harvest tasks for aggregation (midnight job)
    await tasks_collection.create_index(
        [("taskType", 1), ("status", 1), ("scheduledDate", 1)],
        name="idx_tasktype_status_scheduled"
    )
    print("[OK] Created index: taskType + status + scheduledDate")

    # ============================================================
    # 2. BLOCK_ALERTS Collection
    # ============================================================
    print("\n[2/2] Creating block_alerts collection and indexes...")

    # Create collection (if doesn't exist)
    if "block_alerts" not in await db.list_collection_names():
        await db.create_collection("block_alerts")
        print("[OK] Created block_alerts collection")
    else:
        print("[INFO] block_alerts collection already exists")

    # Create indexes for block_alerts
    alerts_collection = db.block_alerts

    # Index 1: Query alerts by farm and status
    await alerts_collection.create_index(
        [("farmId", 1), ("status", 1), ("createdAt", -1)],
        name="idx_farm_status_created"
    )
    print("[OK] Created index: farmId + status + createdAt (desc)")

    # Index 2: Query alerts by block
    await alerts_collection.create_index(
        [("blockId", 1), ("status", 1), ("severity", -1)],
        name="idx_block_status_severity"
    )
    print("[OK] Created index: blockId + status + severity (desc)")

    # Index 3: Query alerts assigned to a user
    await alerts_collection.create_index(
        [("assignedTo", 1), ("status", 1)],
        name="idx_assigned_status",
        sparse=True
    )
    print("[OK] Created index: assignedTo + status (sparse)")

    # Index 4: Unique alert ID
    await alerts_collection.create_index(
        [("alertId", 1)],
        name="idx_alertid_unique",
        unique=True
    )
    print("[OK] Created unique index: alertId")

    # Index 5: Query by category and severity (for filtering)
    await alerts_collection.create_index(
        [("category", 1), ("severity", -1), ("status", 1)],
        name="idx_category_severity_status"
    )
    print("[OK] Created index: category + severity (desc) + status")

    # Index 6: Query alerts reported by user
    await alerts_collection.create_index(
        [("reportedBy", 1), ("createdAt", -1)],
        name="idx_reported_created"
    )
    print("[OK] Created index: reportedBy + createdAt (desc)")

    # ============================================================
    # 3. FARMER_ASSIGNMENTS Collection - Additional Indexes
    # ============================================================
    print("\n[3/3] Checking farmer_assignments collection indexes...")

    # Check if collection exists (should already exist from farm module)
    if "farmer_assignments" in await db.list_collection_names():
        assignments_collection = db.farmer_assignments

        # Get existing indexes
        existing_indexes = await assignments_collection.index_information()
        print(f"[INFO] farmer_assignments collection exists with {len(existing_indexes)} indexes")

        # Check if we need to add any additional indexes
        # The collection should already have userId and farmId indexes from farm_assignment model

        # Compound index for querying active assignments by user
        if "idx_user_active" not in existing_indexes:
            await assignments_collection.create_index(
                [("userId", 1), ("isActive", 1)],
                name="idx_user_active"
            )
            print("[OK] Created index: userId + isActive")
        else:
            print("[INFO] Index userId + isActive already exists")

        # Compound index for querying active assignments by farm
        if "idx_farm_active" not in existing_indexes:
            await assignments_collection.create_index(
                [("farmId", 1), ("isActive", 1)],
                name="idx_farm_active"
            )
            print("[OK] Created index: farmId + isActive")
        else:
            print("[INFO] Index farmId + isActive already exists")
    else:
        print("[WARN] farmer_assignments collection doesn't exist yet")
        print("       (Will be created when first assignment is made)")

    # ============================================================
    # Summary
    # ============================================================
    print("\n" + "=" * 60)
    print("[SUCCESS] Operations Task Manager collections initialized!")
    print("=" * 60)
    print("\nCollections created:")
    print("  1. farm_tasks        - Task management (7 indexes)")
    print("  2. block_alerts      - Issue reporting (6 indexes)")
    print("  3. farmer_assignments - Farm assignments (verified)")
    print("\nNext steps:")
    print("  -> Implement TaskService and TaskGeneratorService")
    print("  -> Create API endpoints for tasks and alerts")
    print("  -> Implement harvest aggregation cron job")
    print("  -> Build mobile-first Operations UI")

    # Close connection
    client.close()
    print("\n[OK] Database connection closed")


if __name__ == "__main__":
    print("=" * 60)
    print("Operations Task Manager - Database Initialization")
    print("=" * 60)
    asyncio.run(init_operations_collections())
