/**
 * AI Dashboard Type Definitions
 *
 * Types for automated farm inspection reports generated by the AI Dashboard service.
 * Reports are produced every 4 hours or on-demand by admins.
 */

// ============================================================================
// RAW INSPECTION DATA
// ============================================================================

export interface FarmCensus {
  totalFarms: number;
  totalBlocks: number;
  blocksByState: Record<string, number>;
  utilization: number;
}

export interface YieldFarmEntry {
  farmId: string;
  farmName: string;
  predictedYieldKg: number;
  actualYieldKg: number;
  efficiency: number;
}

export interface YieldAssessment {
  farms: YieldFarmEntry[];
  globalPredicted: number;
  globalActual: number;
  globalEfficiency: number;
}

export interface GrowthTimeline {
  blocksAhead: number;
  blocksBehind: number;
  blocksOnTime: number;
  details: unknown[];
}

export interface SenseHubAlerts {
  blocksScanned: number;
  blocksWithAlerts: number;
  totalAlerts: number;
  criticalCount: number;
  entries: unknown[];
}

export interface EquipmentHealth {
  blocksScanned: number;
  totalOnline: number;
  totalOffline: number;
  entries: unknown[];
}

export interface AutomationAudit {
  blocksScanned: number;
  totalEnabled: number;
  totalDisabled: number;
  entries: unknown[];
}

export interface HarvestProgress {
  totalHarvests7Days: number;
  totalKg7Days: number;
  gradeDistribution: Record<string, number>;
  recentHarvests: unknown[];
}

export interface PlatformAlerts {
  activeCount: number;
  bySeverity: Record<string, number>;
  topAlerts: unknown[];
}

export interface LabNutrientReading {
  nutrient: string;
  value: number;
  unit: string;
  zone: string;
  timestamp: string | null;
}

export interface CropNutrientTargets {
  cropName: string;
  scientificName: string | null;
  phMin: number | null;
  phMax: number | null;
  phOptimal: number | null;
  ecRangeMs: string | null;
  nutrientsRecommendations: string | null;
  temperatureMin: number | null;
  temperatureMax: number | null;
  temperatureOptimal: number | null;
  humidityMin: number | null;
  humidityMax: number | null;
  humidityOptimal: number | null;
}

export interface LabAnalysisBlockEntry {
  blockId: string;
  blockName: string;
  farmName: string;
  cropName: string | null;
  blockState: string | null;
  daysSincePlanting: number | null;
  currentGrowthStage: string | null;
  totalCycleDays: number | null;
  latestReadings: LabNutrientReading[];
  cropTargets: CropNutrientTargets | null;
  activeFertigationCard: Record<string, unknown> | null;
}

export interface LabAnalysis {
  blocksScanned: number;
  blocksWithLabData: number;
  blocksWithCropTargets: number;
  entries: LabAnalysisBlockEntry[];
}

export interface InspectionRawData {
  farmCensus: FarmCensus | null;
  yieldAssessment: YieldAssessment | null;
  growthTimeline: GrowthTimeline | null;
  senseHubAlerts: SenseHubAlerts | null;
  equipmentHealth: EquipmentHealth | null;
  automationAudit: AutomationAudit | null;
  harvestProgress: HarvestProgress | null;
  platformAlerts: PlatformAlerts | null;
  labAnalysis: LabAnalysis | null;
}

// ============================================================================
// AI SUMMARY
// ============================================================================

export type HealthRating = 'excellent' | 'good' | 'fair' | 'poor' | 'critical';

export type InspectionVerdict = 'pass' | 'warning' | 'fail';

export type RecommendationPriority = 'high' | 'medium' | 'low';

export interface FarmStatusCard {
  farmName: string;
  farmId: string;
  health: string;
  yieldEfficiency: number;
  topIssues: string[];
}

export interface InspectionResult {
  taskName: string;
  verdict: InspectionVerdict;
  summary: string;
}

export interface Recommendation {
  priority: RecommendationPriority;
  category: string;
  message: string;
  affectedFarms: string[];
}

export interface AISummary {
  executiveSummary: string;
  overallHealthRating: HealthRating;
  farmStatusCards: FarmStatusCard[];
  inspectionResults: InspectionResult[];
  recommendations: Recommendation[];
}

// ============================================================================
// DASHBOARD REPORT
// ============================================================================

export type ReportStatus =
  | 'collecting'
  | 'generating'
  | 'completed'
  | 'generation_failed'
  | 'failed';

export interface DashboardReport {
  reportId: string;
  status: ReportStatus;
  triggeredBy: string;
  startedAt: string;
  completedAt: string | null;
  durationSeconds: number | null;
  rawData: InspectionRawData | null;
  aiSummary: AISummary | null;
  error: string | null;
}
