"""Models package"""
from .user import (
    UserRole,
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserInDB,
    UserLogin,
    TokenResponse,
    TokenPayload,
    RefreshTokenCreate,
    RefreshTokenInDB,
    EmailVerificationRequest,
    VerifyEmailRequest,
    PasswordResetRequest,
    PasswordResetConfirm,
    VerificationTokenInDB
)

from .dashboard import (
    ChartSeries,
    ChartWidgetData,
    StatWidgetData,
    ModuleDataSource,
    SystemDataSource,
    ExternalAPIDataSource,
    CCMWidget,
    WidgetDataResponse,
    BulkWidgetDataRequest,
    BulkWidgetDataResponse,
    DashboardLayout,
    DashboardConfig,
)

__all__ = [
    # User models
    "UserRole",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserInDB",
    "UserLogin",
    "TokenResponse",
    "TokenPayload",
    "RefreshTokenCreate",
    "RefreshTokenInDB",
    "EmailVerificationRequest",
    "VerifyEmailRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "VerificationTokenInDB",
    # Dashboard models
    "ChartSeries",
    "ChartWidgetData",
    "StatWidgetData",
    "ModuleDataSource",
    "SystemDataSource",
    "ExternalAPIDataSource",
    "CCMWidget",
    "WidgetDataResponse",
    "BulkWidgetDataRequest",
    "BulkWidgetDataResponse",
    "DashboardLayout",
    "DashboardConfig",
]
